# psd1 template from https://docs.microsoft.com/en-us/powershell/developer/module/how-to-write-a-powershell-module-manifest
# Module manifest for module 'bloggingModule'
#
# Generated by: lmmGitUsername
#
# Generated on: 12/15/2018
#

@{

# Script module or binary module file associated with this manifest
#RootModule = 'bloggingModule.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = ''

# Author of this module
Author = 'lmmGitUsername'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2018 lmmGitUsername. All rights reserved.'

# Description of the functionality provided by this module
# Description = 'Microsoft PowerShell script module for generating the HTML that I use for my journal on a regular basis. This module can be used in command line or in a graphical user interface (GUI).'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = '5.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
# ScriptsToProcess = @("Get-BloggingModuleGUI.ps1","Get-BlogEntry.ps1","Get-ArticleTagsAndDatetime.ps1")

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Get-BlogEntryOneStep'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @('bloggingModule')

# List of all files packaged with this module
# FileList = @("bloggingModule.psm1","Get-BloggingModuleGUI.ps1","Get-ArticleTagsAndDatetime.ps1","Get-LastTimeHeadingInLmmportfolioJournal.ps1","Get-BlogEntry.ps1","README.md","Untitled3.ps1","Untitled4.ps1")

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}